xbyak/xbyak.h
While slabels are being cleared in `LabelManager::reset`, clabel definition lists were not.
=> clear clabel definition lists in LabelManager::reset

xbyak/xbyak.h
Currently `CodeGenerator::resetSize()` doesn't reset `isCalledCalcJmpAddress_` to false, so if you call `CodeGenerator::reset()`, further calls to `CodeGenerator::ready()` will not resolve jmp offsets.
I'm not sure if it's appropriate to make this change to `CodeGenerator::resetSize()` or if it should be done to `CodeGenerator::reset()`, I went with the former.
=> CodeGenerator::resetSize() doesn't reset isCalledCalcJmpAddress_

xbyak/xbyak.h, xbyak/xbyak_mnemonic.h
I've only added support for up to 9-byte nop sequences, as that's all I could seem to find consensus on for both AMD and Intel.
The use case for myself was to emit nop slides to backpatch at a later time.
=> add support for multibyte nop sequences

xbyak/xbyak_util.h
Hi,
Here is the PR promised by @rsdubtso to support querying core numbers and cache topologies on Intel cpus.
=> Adding queries to get the cpu topology on Intel architectures.

xbyak/xbyak_util.h
If the default value is 0 and the cpu has no leaf B, then in the loop
on the subleaves of leaf 4, the number of cores sharing a data cache will be 0.
=> Change default value for n_cores in setCacheHierarchy.

xbyak/xbyak.h
Sorry I did not catch this earlier.
clang prior the 3.9 version requires a user-provided default constructor to be const-default-constructible.
https://stackoverflow.com/questions/7411515/why-does-c-require-a-user-provided-default-constructor-to-default-construct-a
=> Fixes an error raised by clang < 3.9

xbyak/xbyak_util.h
This is a slight rework of the previous fix in the Xbyak (commit fe083912c8ac7b7e2b0081cbd6213997bc8b56e6). This patch makes the logic a bit clearer. (Some discussion at https://github.com/intel/mkl-dnn/issues/208.)
=> Account for potentially zero 0xb leaf when parsing cache/topology via cpuid

xbyak/xbyak.h, xbyak/xbyak_util.h
Query cpuid for Intel CPU which support x2APIC for number of physical and logical cores per socket.
=> Get num of cores using x2APIC ID

xbyak/xbyak.h
Hi Herumi,
This change reduces the hardened ruhtime entitlements required by the JIT-ed code on macOS down to [com.apple.security.cs.allow-jit](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_allow-jit) by specifying the `MAP_JIT` flag to `mmap()`.
=> specify MAP_JIT mmap flag on macOS

sample/calc.cpp
Segmentation fault occurred in `calc` sample
when no variables are given from command line argument:
```
$ cd sample
$ make calc64
$ ./calc64 "" "123"
varTbl = { }
64bit mode
zsh: segmentation fault  ./calc64 "" "123"
```
`put` function always access `x[0]`,
but segmentation fault occurred when `x.size() == 0`.
=> Fix segmentation fault in calc sample

xbyak/xbyak_util.h
Hypervisors may indicate x2APIC support but sill have zeroes in the 0xb leaf. This patch slightly improves behavior in such a case.
=> fix for zeroed-out 0xb leaf

xbyak/xbyak.h
This allows only requiring `com.apple.security.cs.allow-jit` entitlement with hardened runtime even if built with Xcode 9 which does not have MAP_JIT.
Related: https://github.com/herumi/xbyak/issues/93, https://github.com/pytorch/pytorch/issues/39990
=> use MAP_JIT on macOS regardless of Xcode version

gen/Makefile, gen/gen_amx.cpp, gen/update.bat, xbyak/xbyak.h, xbyak/xbyak_mnemonic.h, xbyak/xbyak_util.h
Add support of Intel® AMX instruction set described in updated Intel® Architecture Instruction Set Extensions and Future Features Programming Reference (https://software.intel.com/content/dam/develop/public/us/en/documents/architecture-instruction-set-extensions-programming-reference.pdf)
=> Add support of Intel® AMX instruction set

xbyak/xbyak.h
`winsock2.h` is a very noisy inclusion and not necessary as far as I can tell for using xbyak on Windows. It makes including `xbyak.h` order dependent because it must be included prior to `Windows.h` otherwise compilation explodes.
=> Remove #include <winsock2.h>

xbyak/xbyak.h
Some compilers may not support __declspec(thread) but they can build apps using >= C++11 by default.
=> Use thread_local for XBYAK_TLS when supported

xbyak/xbyak_util.h
getNumConst doesn't change Cpu state but is not marked const.
=> Cpu: make getNumCores constant

xbyak/xbyak.h
This PR updates the exception-less error handling by (i) having a static TLS `l_error` in the scope of `int l_err()` function, and (ii) making this function `inline` which ensures that there will be only one definition of the function in a project. Ultimately, instead of having one `l_err` per object file, this PR enables having one `l_err` for an entire project.
=> make Xbyak::local::l_err inline with block scope static TLS l_error

xbyak/xbyak_util.h
This was locking feature checks between Intel and AMD.
Most of the features overlap between AMD and Intel for extended flag
information in fn8000_0001.
Fixes detection of LZCNT/ABM on my Zen+ CPU
=> Fixes extended feature support checking

gen/Makefile, gen/gen_avx512.cpp, gen/gen_vnni.cpp, gen/update.bat, xbyak/xbyak.h, xbyak/xbyak_mnemonic.h, xbyak/xbyak_util.h
Add support of Intel® AVX-VNNI instruction set described in updated [Intel® Architecture Instruction Set Extensions Programming Reference](https://software.intel.com/content/www/us/en/develop/download/intel-architecture-instruction-set-extensions-programming-reference.html)
=> Add support of Intel® AVX-VNNI instruction set

xbyak/xbyak.h
This fixes a compile error on some older macOS versions. The error is caused by not checking whether `MAP_ANONYMOUS` is available if `XBYAK_USE_MAP_JIT` is enabled.
=> fixed compile error on some older macOS versions

CMakeLists.txt, cmake/config.cmake.in
`configure_file` has been superseded by `configure_package_config_file`.
Also add the `config-version.cmake` file, allowing to do:
```
find_package(xbyak 5.994 REQUIRED)
target_link_libraries(project PRIVATE xbyak::xbyak)
```
=> fix cmake config files

xbyak/xbyak_util.h
Checking for non-zero means that calls like `has(tAVX512F | tAVX512VL)`
may _not_ work in the case that _only one_ of the checked flags are
true, since it only masks the bit-flag and checks for non-zero, when it
should mask the bits and then check if it equals the mask again to
ensure that all bits are active.
Currently, the user has to call `has` multiple times:
```cpp
if( cpu.has(tAVX512F) && cpu.has(tAVX512VL) && cpu.has(tAVX512BW) )
{
...
}
```
this PR allows them all to be checked in parallel with one call
```cpp
if( cpu.has(tAVX512F | tAVX512VL | tAVX512BW) )
{
...
}
```
=> Allow parallel feature checks

xbyak/xbyak.h
Hi, I think that since the 32-bit displacement is interpreted as a signed value, the sign bit should match the high bits of the 64-bit representation of the displacement. Otherwise, conversion to s32 value can truncate and something like 2^31 can be interpreted as -2^31.
=> fix condition to throw error for invalid displacements

test/Makefile
.asm, .lst, and .obj files get generated during tests, and they should be cleaned up as well
=> build(make): fix clean target in test/Makefile

gen/Makefile, sample/Makefile, test/Makefile
It is currently impossible to pass custom flags to the makefiles using environment variables, because they ignore the predefined macros `CXXFLAGS`, `CPPFLAGS` and `LDFLAGS`.
Passing `LDFLAGS` is defined in the Posix standard (https://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html#tag_20_76_13_09), while the `CXXFLAGS` and `CPPFLAGS` variables are predefined in GNU Make (https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html#Implicit-Variables).
=> build(make): honour CXXFLAGS, CPPFLAGS and LDFLAGS

xbyak/xbyak.h
The syscall is wrapped in Bionic from API version 30:
https://android.googlesource.com/platform/bionic.git/+/3d24d2b0883e%5E!/
This fixes the build for earlier versions of Android. Note that
MDF_CLOEXEC as well as the raw syscall numbers for memfd_create
were added much earlier:
https://android.googlesource.com/platform/bionic.git/+/82d7504cd7d5%5E!/
=> memfd_create: fix build for ANDROID_API < 30

doc/install.md
xbyak is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for xbyak and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build xbyak, ready to be included in their projects.
We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64) to keep a wide coverage for users.
I'm a maintainer for vcpkg, and [here is what the port script looks like](https://github.com/microsoft/vcpkg/blob/master/ports/xbyak/portfile.cmake). We try to keep the library maintained as close as possible to the original library. :)
=> Add vcpkg installation instructions

test/Makefile, test/test_address.sh, test/test_avx.sh, test/test_avx512.sh, test/test_nm.sh
Also add `$(CFLAGS)` to the detect_x32 target as they may be required to successfully detect the host system.
=> test: simplify makefile

.github/workflows/main.yml, sample/Makefile
GitHub's CI default runners are full of all kinds of software, and this can cause hard to reproduce errors. Luckly, GitHub Actions supports running jobs in a container image, so that the build environment is minimal and reprocucible.
This patch changes the main CI job to run in a Debian Testing container, fixing the issues described in
<https://github.com/herumi/xbyak/commit/cfb1127c3bf28d55e68b367a0a6944829a5c025d>.
As Debian Testing is a semi-rolling relase distribution, and nasm 2.15 is shipped by default, I've also modified the script to install nasm from apt instead of building it from source.
=> ci: use containers

xbyak/xbyak_util.h
This allows for a compile-time alias of multiple CPU flag types:
```
Xbyak::util::Cpu host_caps;
...
using namespace Xbyak::util;
static constexpr auto AVX512Ortho = Cpu::tAVX512F | Cpu::tAVX512VL;
static constexpr auto AVX512OrthoFloat = AVX512Ortho | Cpu::tAVX512DQ;
if (host_caps.has(AVX512Ortho))
{
...
}
```
=> Allow constexpr TypeT `operator|`

CMakeLists.txt
With CMake 3.27, the following deprecation warning is visible:
```
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
```
Version 3.5 was released in March 2016 and is available on Ubuntu 14.04 (package `cmake3`) and later
=> build(cmake): bump minimum required to version 3.5

test/Makefile
This fixes tests on 32 bit systems.
=> test: only run apx test when BIT=64

xbyak/xbyak_util.h
ARM64EC is a custom ABI designed to allow ARM64 code to directly call into x64 code and vice-versa. In order to facilitate this, `__x86_64__` (in llvm) and _M_X64 (in msvc) are both defined, but most x64 intrinsics aren't supported, so don't attempt to use them.
=> support building for arm64ec

xbyak/xbyak.h
This commit 33882d0a0906c61455324cd69d8372460e23741c has removed support for `align` with `Auto grow` enabled. Re-enabling it.
Please let me know if there were any other issues that blocks enabling it.
=> support align for auto_grow

xbyak/xbyak_util.h
- FIX: `setCacheHierarchy()` threw a div-by-zero exception on legacy AMD CPUs.
- Improved detection of cores/threads for legacy AMD CPUs in `setNumCores()`.
- Improved cache hierarchy detection for AMD and Intel CPUs in `setCacheHierarchy()`.
- FIX: Typo `coresSharignDataCache_` -> `coresSharingDataCache_`.
- Compare the full manufacturer ID strings to detect CPU manufacturers (AMD or Intel).
- `getCpuid()` now calls `getCpuidEx()` internally.
- `setFamily()` now utilizes `extractBit()`.
- FIX: If `CPU family == 6` then only add `extModel << 4` to `model` on Intel CPUs.
- Renamed `IntelCpuTopologyLevel` to `CpuTopologyLevel` as both Intel and modern AMD CPUs support the feature.
- Removed no longer used functions: `mask()` and `get32bitAsBE()`.
- Removed no longer used `x2APIC_supported_` …
=> Improvements to core count and cache hierarchy detection.

meson.build
This patch fixes a couple of issues introduced in commits c7c1eac070851068d7adc3a67ad2efd196145687 and
9f535729159baf467c3bd8dc7ec017a40289a12c:
- Dropped `dataonly: true` from `pkgconfig.generate()`, since it generates a .pc file unsuitable for libraries. Instead, I've just set `install_dir` to `$datadir/pkgconfig`, which generates the following:
$ cat /usr/share/pkgconfig/xbyak.pc
prefix=/usr
includedir=${prefix}/include
Name: xbyak
Description: JIT assembler for x86(IA32), x64(AMD64, x86-64)
URL: https://github.com/herumi/xbyak
Version: 7.06
Cflags: -I${includedir}
- Changed `share/cmake/xbyak` to `get_option('datadir')/'cmake'/meson.project_name()` to avoid hardcoding "share" as the datadir.
- Added `arch_independent: true` to the `cmake.write_basic_package_version_file()` call so …
=> build(meson): arch-independent fixes

.github/workflows/main.yml
Fix warning:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
=> Update actions/checkout to v4

xbyak/xbyak.h
While the functionality to access, for example, `al` from `eax` by calling `reg.cvt8()` exists, this does not exist for `xmm`/`ymm`/`zmm` registers. This is useful, for example, when one has a `ymm` register being initialized from a 128-bit load, implicitly zeroing the upper part, by doing `vmovdqa(ymm.cvt128(), xword[...])`.
This PR adds this functionality in what I think is the most straightforward way possible.
=> add cvt128, cvt256, cvt512 convenience functions

CMakeLists.txt
For the same purpose as [**this PR**](https://github.com/herumi/xbyak/pull/178).
Since CMake 3.31.0, the minimum version below 3.10 generates a warning.
=> CMake: Bump minimum required version to 3.10

xbyak/xbyak.h, xbyak/xbyak_mnemonic.h
These source changes fix the lack of APX encoding for instructions with New Data Destination format (NDD): SAL, SAR, SHL, SHR, RCL, RCR, ROL, ROR, and IMUL.
Xbyak doesn't produce NDD encoding for some instructions unless they use r16-r31 as input.
For example, this sequence:
```asm
sal(rax, r8,   1);
sar(rax, r9,   4);
shl(rax, rdi,  8);
shr(rax, rsi, 12);
rcl(rax, r10, 16);
rcr(rax, r11, 20);
rol(rax, r14, 24);
ror(rax, r15, 28);
sal(rcx, qword[r8],  32);
sar(rcx, qword[r9],  36);
sal(rcx, qword[rdi], 40);
sar(rcx, qword[rsi], 44);
rcl(rcx, qword[r10], 48);
rcr(rcx, qword[r11], 52);
rol(rcx, qword[r14], 56);
ror(rcx, qword[r15], 60);
```
is produced into this binary:
```asm
49 d1 e0                shl    r8,1
49 c1 f9 04             sar    r9,0x4
48 c1 e7 08             shl    rdi,0x8
48 …
```
=> Fix improper encoding of APX instructions with NDD format.

sample/Makefile, test/Makefile
Instead of explicitly passing -m32 and -m64 to the CXX invocation, define CXX_32 and CXX_64 as "CXX -m32" and "CXX -m64", respectively.
This allows easily using a cross GCC toolchain instead of GCC's multilib support, for example by defining CXX_32=i686-linux-gnu-gcc, and CXX_64=x86_64-linux-gnu-gcc.
See
<https://lists.debian.org/msgid-search/20250316194848.GA2297362@subdivi.de> and related messages for some more context on why multilib (-m32 and -m64) might get removed from Debian in the future, in favour of cross compilers.
=> Add CXX_32 and CXX_64 variables in the makefiles

xbyak/xbyak.h
In version 7.26 it is required to use sibmem. However, ldtilecfg/sttilecfg can take any m512 location. This patch allows any addressing for these two instructions.
=> Allow m512 in ldtilecfg/sttilecfg.

test/Makefile, test/jmp.cpp, test/noexception.cpp, xbyak/xbyak.h
Intention of this patch is to support clean build with stricter compiler settings.
Related patch in xbyak_riscv: https://github.com/herumi/xbyak_riscv/pull/19
=> Add override specifiers to virtual methods and -Wsuggest-override flag
